# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Atlantis-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Atlantis-Example
  pod 'atlantis-proxyman', :path => '../atlantis-proxyman.podspec'
end
